en:
    - deposition-process
    - deposition-agreement
    - filenames-formats-metadata
    - faq
    - further-guidance
    - technical-setup
    - api-access
    - collection-policy
    - preservation-policy
    - privacy-policy
    - terms-of-use
    - about-arche
de: 
    - einreichungsprozess 
    - datenuebergabevertrag
    - dateinamen-formate-metadaten
    - faq-de
    - weiterfuehrende-informationen
    - technischer-aufbau
    - api-zugriff
    - sammlungsstrategie
    - konservierungsrichtlinien
    - datenschutzbestimmungen
    - nutzungsbedingungen
    - ueber-arche
    
