en:
    - deposition-process
    - deposition-agreement
    - filenames-formats-metadata
    - faq
    #- further-guidance
    #- technical-setup
    #- api-access
    #- collection-policy
    #- preservation-policy
    #- privacy-policy
    #- terms-of-use
    #- about-arche
#de: 
    #- de/einreichungsprozess 
    #- de/datenuebergabevertrag
    #- de/dateinamen-formate-metadaten
    #- de/faq-de
    #- de/weiterfuehrende-informationen
    #- de/technischer-aufbau
    #- de/api-zugriff
    #- de/sammlungsstrategie
    #- de/konservierungsrichtlinien
    #- de/datenschutzbestimmungen
    #- de/nutzungsbedingungen
    #- de/ueber-arche
    
